AWSTemplateFormatVersion: 2010-09-09
Metadata:
  'AWS::CloudFormation::Designer':
    37fa8c8e-5911-49c5-8cd6-fb60cbee1218:
      size:
        width: 590
        height: 350
      position:
        x: 270
        'y': 130
      z: 0
      embeds:
        - 913e5226-4c25-47b9-afc9-a8fec25df1cd
        - 25791523-df86-4db2-a47a-faab9b60fd0b
        - 95e50971-d3f4-4f01-b128-28b7dd01c8e0
        - 4898c902-f047-495b-ae80-3cbeb5ffe4c1
        - 0ab315bf-380f-48da-aa88-c66b5bf18cde
    913e5226-4c25-47b9-afc9-a8fec25df1cd:
      size:
        width: 140
        height: 140
      position:
        x: 320
        'y': 180
      z: 1
      parent: 37fa8c8e-5911-49c5-8cd6-fb60cbee1218
      embeds:
        - f69f3ffe-927f-4396-8440-c08e796de008
    4898c902-f047-495b-ae80-3cbeb5ffe4c1:
      size:
        width: 140
        height: 140
      position:
        x: 660
        'y': 190
      z: 1
      parent: 37fa8c8e-5911-49c5-8cd6-fb60cbee1218
      embeds: []
    95e50971-d3f4-4f01-b128-28b7dd01c8e0:
      size:
        width: 140
        height: 93
      position:
        x: 320
        'y': 370
      z: 1
      parent: 37fa8c8e-5911-49c5-8cd6-fb60cbee1218
      embeds: []
    25791523-df86-4db2-a47a-faab9b60fd0b:
      size:
        width: 140
        height: 97
      position:
        x: 650
        'y': 360
      z: 1
      parent: 37fa8c8e-5911-49c5-8cd6-fb60cbee1218
      embeds: []
    07e80487-0f96-4d0a-8d77-e2b1ecaf1bc1:
      size:
        width: 60
        height: 60
      position:
        x: 525
        'y': -7
      z: 0
      embeds: []
    0ab315bf-380f-48da-aa88-c66b5bf18cde:
      size:
        width: 60
        height: 60
      position:
        x: 550
        'y': 240
      z: 1
      parent: 37fa8c8e-5911-49c5-8cd6-fb60cbee1218
      embeds: []
      iscontainedinside:
        - f69f3ffe-927f-4396-8440-c08e796de008
        - f69f3ffe-927f-4396-8440-c08e796de008
        - f69f3ffe-927f-4396-8440-c08e796de008
        - f69f3ffe-927f-4396-8440-c08e796de008
    17093562-5357-419f-b125-c6bf811c5bd0:
      source:
        id: 37fa8c8e-5911-49c5-8cd6-fb60cbee1218
      target:
        id: 07e80487-0f96-4d0a-8d77-e2b1ecaf1bc1
      z: 0
    f69f3ffe-927f-4396-8440-c08e796de008:
      size:
        width: 80
        height: 80
      position:
        x: 360
        'y': 210
      z: 2
      parent: 913e5226-4c25-47b9-afc9-a8fec25df1cd
      embeds: []
Resources:
  PublicSubnet1:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VPCL00170144
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 4898c902-f047-495b-ae80-3cbeb5ffe4c1

  PublicSubnet2:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VPCL00170144
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 913e5226-4c25-47b9-afc9-a8fec25df1cd

  PrivateSubnet1:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VPCL00170144
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 95e50971-d3f4-4f01-b128-28b7dd01c8e0

  PrivateSubnet2:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VPCL00170144
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 25791523-df86-4db2-a47a-faab9b60fd0b

  VPCL00170144:
    Type: 'AWS::EC2::VPC'
    Properties: {}
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 37fa8c8e-5911-49c5-8cd6-fb60cbee1218
        
  InternetGateway:
    Type: 'AWS::EC2::InternetGateway'
    Properties: {}
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 07e80487-0f96-4d0a-8d77-e2b1ecaf1bc1

  VPCGatewayAttachment:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !Ref VPCL00170144
      InternetGatewayId: !Ref InternetGateway
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 17093562-5357-419f-b125-c6bf811c5bd0

  PublicRouter:
    Type: 'AWS::EC2::Route'
    Properties:
      RouteTableId: !Ref RouterTable
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 0ab315bf-380f-48da-aa88-c66b5bf18cde

  RouterTable:
    Type: 'AWS::EC2::RouteTable'
    Properties: {}
    Metadata:
      'AWS::CloudFormation::Designer':
        id: f69f3ffe-927f-4396-8440-c08e796de008
