AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  ExportVpcStackName:
    Type: String

Resources:
  NG1EIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: EIP 1 
        
  NG2EIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: EIP 2 
