AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  VpcCidr:
    Default: 10.0.0.0/20
    Type: String

  PublicSubnet1CIDR:
    Default: 10.0.0.0/24
    Type: String

  PublicSubnet2CIDR:
    Default: 10.0.4.0/24
    Type: String

  PrivateSubnet1CIDR:
    Default: 10.0.8.0/24
    Type: String

  PrivateSubnet2CIDR:
    Default: 10.0.12.0/24
    Type: String

Resources:
#Subnets
  PublicSubnet1:
    Type: 'AWS::EC2::Subnet'
    Properties:
      # AvailabitiyZone: !Select [ 0, !GetAZs '' ]      
      VpcId: !Ref VPCL00170144
      CidrBlock: !Ref PublicSubnet1CIDR

  PublicSubnet2:
    Type: 'AWS::EC2::Subnet'
    Properties:
      # AvailabitiyZone: !Select [ 1, !GetAZs '' ]
      VpcId: !Ref VPCL00170144
      CidrBlock: !Ref PublicSubnet2CIDR

  PrivateSubnet1:
    Type: 'AWS::EC2::Subnet'
    Properties:
      # AvailabitiyZone: !Select [ 0, !GetAZs '' ]
      VpcId: !Ref VPCL00170144
      CidrBlock: !Ref PrivateSubnet1CIDR

  PrivateSubnet2:
    Type: 'AWS::EC2::Subnet'
    Properties:
      # AvailabitiyZone: !Select [ 1, !GetAZs '' ]
      VpcId: !Ref VPCL00170144
      CidrBlock: !Ref PrivateSubnet2CIDR

  VPCL00170144:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 10.0.0.0/20
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: Assignment VPC

  InternetGateway:
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        - Key: Name
          Value: Assignment IGW     

  VPCGatewayAttachment:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !Ref VPCL00170144
      InternetGatewayId: !Ref InternetGateway

#Public route table
  PublicRouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref VPCL00170144

  PublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet1

  PublicSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet2

#Private route table
  PrivateRouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref VPCL00170144

  PrivateSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      SubnetId: !Ref PrivateSubnet1

  PrivateSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      SubnetId: !Ref PrivateSubnet2

